const jobData = [
  {
    companyName: "BASMA Marble Restoration Co.W.L.L",
    jobTitle: "Construction Laborer",
    description:
      "Seeking hardworking Construction Laborers for various projects in Dubai.",
    location: "Bahrain",
    date: "Oct 01, 2024",
    type: "Full-Time",
    salary: "100 BD/month",
    overtime: "Overtime Available",
    workdays: "6 days/week (8hrs)",
    benefits: "Food & Accommodation",
    img:"/joblogo/logo2.jpeg",
    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "Quick Zebra Services",
    jobTitle: "Dock Worker",
    description:
      "Dock Workers needed for cargo handling at the port of Los Angeles.",
    location: "Bahrain",
    date: "Sept 27, 2024",
    type: "Part-Time",
    salary: "100 BD/month",
    overtime: "Overtime",
    workdays: "6 days/week (8hrs)",
    benefits: "Health Insurance",
    img:"/joblogo/logo3.jpeg",


    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "Proworks Recruitment Services",
    jobTitle: "Front-End Developer",
    description:
      "Looking for a skilled Front-End Developer to join our innovative team in London.",
    location: "Dubai,UAE",
    date: "Oct 5, 2024",
    type: "Full-Time",
    salary: "1000 AED/month",
    overtime: "According to Company Rule",
    workdays: "6 days/week (10hrs)",
    benefits: "Remote Work & Health Insurance",
    img:"/joblogo/logo6.jpeg",

    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "Paragon Employment Services L.LC",
    jobTitle: "Farm Worker",
    description:
      "We need dedicated Farm Workers to assist in our harvest season in New Zealand.",
    location: "Dubai,UAE",
    date: "Oct 5, 2024",
    type: "Seasonal",
    salary: "1000 AED/month",
    overtime: "Overtime Available",
    workdays: "6 days/week (8hrs)",
    benefits: "Accommodation & Meals",
    img:"/joblogo/logo1.jpeg",

    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "Innovation Direct EMployee Services",
    jobTitle: "Tour Guide",
    description:
      "Seeking a passionate Tour Guide for guiding tourists across Europe.",
    location: "Dubai,UAE",
    date: "Sept 26, 2024",
    type: "Contract",
    salary: "1300 AED/month",
    overtime: "No Overtime",
    workdays: "6 days/week (8hrs)",
    benefits: "Travel Expenses Covered",
    img:"/joblogo/logo4.jpeg",

    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "Koheji Contactors WLL",
    jobTitle: "Software Developer",
    description:
      "Join our team of developers to create innovative software solutions.",
    location: "Bahrain",
    date: "Oct 6, 2024",
    type: "Full-Time",
    salary: "100 BD/month",
    overtime: "No Overtime",
    workdays: "6 days/week (8hrs)",
    benefits: "Remote Work Option",
    img:"/joblogo/logo5.jpeg",

    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "UrbanBuild",
    jobTitle: "Civil Engineer",
    description:
      "Experienced Civil Engineer needed for urban development projects in Singapore.",
    location: "Singapore",
    date: "November 5, 2024",
    type: "Full-Time",
    salary: "90,000 SGD/year",
    overtime: "Occasional Overtime",
    workdays: "5 days/week (9hrs)",
    benefits: "Housing Allowance & Insurance",
    img:"/joblogo/logo1.jpeg",

    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "HealthFirst Medical Center",
    jobTitle: "Registered Nurse",
    description:
      "Registered Nurses needed for our growing medical team in Toronto.",
    location: "Toronto, Canada",
    date: "November 20, 2024",
    type: "Full-Time",
    salary: "75,000 CAD/year",
    overtime: "Occasional Overtime",
    workdays: "5 days/week (8hrs)",
    benefits: "Health & Dental Insurance",
    img:"/joblogo/logo2.jpeg",

    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
];

export default jobData;
