const jobData = [
  {
    companyName: "Emirates Gas Pvt. Ltd",
    jobTitle: "Construction Laborer",
    description:
      "Seeking hardworking Construction Laborers for various projects in Dubai.",
    location: "Dubai, UAE",
    date: "August 31, 2024",
    type: "Full-Time",
    salary: "100 AED/day",
    overtime: "Overtime Available",
    workdays: "6 days/week (8hrs)",
    benefits: "Food & Accommodation",
    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "Blue Ocean Shipping",
    jobTitle: "Dock Worker",
    description:
      "Dock Workers needed for cargo handling at the port of Los Angeles.",
    location: "Los Angeles, USA",
    date: "September 15, 2024",
    type: "Part-Time",
    salary: "80 USD/day",
    overtime: "Overtime Available",
    workdays: "5 days/week (7hrs)",
    benefits: "Health Insurance",
    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "TechWave Inc.",
    jobTitle: "Front-End Developer",
    description:
      "Looking for a skilled Front-End Developer to join our innovative team in London.",
    location: "London, UK",
    date: "September 20, 2024",
    type: "Full-Time",
    salary: "60,000 GBP/year",
    overtime: "Occasional Overtime",
    workdays: "5 days/week (8hrs)",
    benefits: "Remote Work & Health Insurance",
    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "GreenFields Agriculture",
    jobTitle: "Farm Worker",
    description:
      "We need dedicated Farm Workers to assist in our harvest season in New Zealand.",
    location: "Wellington, New Zealand",
    date: "October 1, 2024",
    type: "Seasonal",
    salary: "25 NZD/hour",
    overtime: "Overtime Available",
    workdays: "6 days/week (7hrs)",
    benefits: "Accommodation & Meals",
    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "Global Travels",
    jobTitle: "Tour Guide",
    description:
      "Seeking a passionate Tour Guide for guiding tourists across Europe.",
    location: "Berlin, Germany",
    date: "October 15, 2024",
    type: "Contract",
    salary: "50 EUR/hour",
    overtime: "No Overtime",
    workdays: "5 days/week (6hrs)",
    benefits: "Travel Expenses Covered",
    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "StarTech Solutions",
    jobTitle: "Software Developer",
    description:
      "Join our team of developers to create innovative software solutions.",
    location: "San Francisco, USA",
    date: "October 10, 2024",
    type: "Full-Time",
    salary: "120,000 USD/year",
    overtime: "No Overtime",
    workdays: "5 days/week (8hrs)",
    benefits: "Remote Work Option",
    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "UrbanBuild",
    jobTitle: "Civil Engineer",
    description:
      "Experienced Civil Engineer needed for urban development projects in Singapore.",
    location: "Singapore",
    date: "November 5, 2024",
    type: "Full-Time",
    salary: "90,000 SGD/year",
    overtime: "Occasional Overtime",
    workdays: "5 days/week (9hrs)",
    benefits: "Housing Allowance & Insurance",
    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
  {
    companyName: "HealthFirst Medical Center",
    jobTitle: "Registered Nurse",
    description:
      "Registered Nurses needed for our growing medical team in Toronto.",
    location: "Toronto, Canada",
    date: "November 20, 2024",
    type: "Full-Time",
    salary: "75,000 CAD/year",
    overtime: "Occasional Overtime",
    workdays: "5 days/week (8hrs)",
    benefits: "Health & Dental Insurance",
    icons: {
      location: "ep:location",
      date: "uiw:date",
      type: "mingcute:time-line",
      salary: "dashicons:money-alt",
      overtime: "mdi:sort-time-descending-outline",
      workdays: "material-symbols:work-history-outline",
      benefits: "lucide-lab:houses",
    },
  },
];

export default jobData;
